*Task 1;
*Create the permanent library;
libname mylib;
*read the text file into SAS;
data mylib.lab_2;
infile 'lab_2.txt';
input consumption income;
run;
proc print data=mylib.lab_2 (obs=20);
title1 'Task 1 Printout';
footnote 'SAS program by Syed Mahmood';
run;
*Task 2;
data mylib.temp;
set mylib.lab_2;
saving = income - consumption;
keep saving;
run;
proc print data=mylib.temp (obs=20);
title2 'Task 2 Printout';
footnote 'SAS program by Syed Mahmood';
run;
*Task 3;
data mylib.temp2;
set mylib.temp;
if saving < 0 then delete;
run;
proc print data=mylib.temp2 (obs=20);
title3 'Task 3 Printout';
footnote 'SAS Program by Syed Mahmood';
run;
*Task 4;
data big;
set mylib.lab_2;
if income < 2000 then delete;
run;
proc print data=big;
title4 'Task 4 Printout (Bigger than 2000)';
footnote 'SAS Program by Syed Mahmood';
run;

data small;
set mylib.lab_2;
if income > 2000 then delete;
run;
proc print data=small;
title5 'Task 4 Printout (Smaller than 2000)';
footnote 'SAS Program by Syed Mahmood';
run;
